release:
  branches:
    - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  -
    - semantic-release-replace-plugin
    - replacements:
        - files:
            - modules/servers/upCloudVps/lib/upCloudVps.php
          from: "'MODULE_VERSION', '.+?'"
          to: "'MODULE_VERSION', '${nextRelease.version}'"
          results:
            - file: modules/servers/upCloudVps/lib/upCloudVps.php
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
  -
    - "@semantic-release/git"
    - assets:
        - modules/servers/upCloudVps/lib/upCloudVps.php
      message: "chore: release ${nextRelease.version} [skip ci]"
  - "@semantic-release/github"
